### ISSUE TITLE
Running the Unit Tests

### ISSUE THREAD

**Issue by kw90** [PatrickTrentin88/omt_python_examples#1]
Hi again :)

was searching for a solution to set a hard timeout for `OptiMathSAT` and stumbled upon your repository.

After installing and building the required dependencies (`Python3.6`, `python3-dev`, `libgmp-dev`) on a Ubuntu 18.04 machine, I got the required `lib/_optimathsat.so` and `include/optimathsat.py` files.

Unfortunately, when trying to run the `unit-tests/timeout.py` I get the following error:

```
➜ python3 unit-tests/timeout.py 
Traceback (most recent call last):
  File "/home/kw/source/omt_python_examples/unit-tests/../include/optimathsat.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 657, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 556, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1101, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /home/kw/source/omt_python_examples/unit-tests/../lib/_optimathsat.so: undefined symbol: _ZNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEC1Ev

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "unit-tests/timeout.py", line 24, in <module>
    from wrapper import * # pylint: disable=unused-wildcard-import,wildcard-import
  File "/home/kw/source/omt_python_examples/unit-tests/../include/wrapper.py", line 8, in <module>
    from optimathsat import * # pylint: disable=unused-wildcard-import,wildcard-import
  File "/home/kw/source/omt_python_examples/unit-tests/../include/optimathsat.py", line 17, in <module>
    _mathsat = swig_import_helper()
  File "/home/kw/source/omt_python_examples/unit-tests/../include/optimathsat.py", line 16, in swig_import_helper
    return importlib.import_module('_optimathsat')
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /home/kw/source/omt_python_examples/unit-tests/../lib/_optimathsat.so: undefined symbol: _ZNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEC1Ev
```

There seems to be a undefined symbol `_ZNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEC1Ev` in my generated `lib/_optimathsat.so`. Do you know how I can fix this?

Thanks you for your help.

```
➜ uname -a
Linux kw-asus 5.3.0-45-generic #37~18.04.1-Ubuntu SMP Fri Mar 27 15:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by PatrickTrentin88** [comment]
@kw90 Ubuntu 18.04 ships with older versions of `gcc` and `g++`, I would recommend Ubuntu 20.04 for an out-of-the-box experience.

**note:** the distributable package of OptiMathSAT contains an example of a SMT-LIB formula with a timeout. However, I would recommend to rely on an external program (e.g. `timeout`) to force OptiMathSAT to terminate. Be sure to send a `SIGKILL` signal and not others.

**Comment by kw90** [comment]
I see. I'll try it on my Arch machine then. What versions of `gcc` and `g++` are required?

On my Arch machine ATM I currently run version 9.3.0:

```zsh
➜ gcc --version                                          
gcc (Arch Linux 9.3.0-1) 9.3.0
```

```zsh
➜ g++ --version
g++ (Arch Linux 9.3.0-1) 9.3.0
```

Thanks for the tip with the external `SIGKILL`!

**Comment by kw90** [comment]
With version 9.3.0 of `gcc` and `g++` it works! Thanks!

**Comment by PatrickTrentin88** [comment]
YW!

Closing, nothing else needs to be done.
